#pragma once

#if defined(__X86_64_SYSCALLS__)
    #define _SYS_READ                   0
    #define _SYS_WRITE                  1
    #define _SYS_OPEN                   2
    #define _SYS_CLOSE                  3
    #define _SYS_STAT                   4
    #define _SYS_FSTAT                  5
    #define _SYS_LSTAT                  6
    #define _SYS_POLL                   7
    #define _SYS_LSEEK                  8
    #define _SYS_MMAP                   9
    #define _SYS_MPROTECT               10
    #define _SYS_MUNMAP                 11
    #define _SYS_BRK                    12
    #define _SYS_RT_SIGACTION           13
    #define _SYS_RT_SIGPROCMASK         14
    #define _SYS_RT_SIGRETURN           15
    #define _SYS_IOCTL                  16
    #define _SYS_PREAD64                17
    #define _SYS_PWRITE64               18
    #define _SYS_READV                  19
    #define _SYS_WRITEV                 20
    #define _SYS_ACCESS                 21
    #define _SYS_PIPE                   22
    #define _SYS_SELECT                 23
    #define _SYS_SCHED_YIELD            24
    #define _SYS_MREMAP                 25
    #define _SYS_MSYNC                  26
    #define _SYS_MINCORE                27
    #define _SYS_MADVISE                28
    #define _SYS_SHMGET                 29
    #define _SYS_SHMAT                  30
    #define _SYS_SHMTL                  31
    #define _SYS_DUP                    32
    #define _SYS_DUP2                   33
    #define _SYS_PAUSE                  34
    #define _SYS_NANOSLEEP              35
    #define _SYS_GETITIMER              36
    #define _SYS_ALARM                  37
    #define _SYS_SETITIMER              38
    #define _SYS_GETPID                 39
    #define _SYS_SENDFILE               40
    #define _SYS_SOCKET                 41
    #define _SYS_CONNECT                42
    #define _SYS_ACCEPT                 43
    #define _SYS_SENDTO                 44
    #define _SYS_RECVFROM               45
    #define _SYS_SENDMSG                46
    #define _SYS_RECVMSG                47
    #define _SYS_SHUTDOWN               48
    #define _SYS_BIND                   49
    #define _SYS_LISTEN                 50
    #define _SYS_GETSOCKNAME            51
    #define _SYS_GETPEERNAME            52
    #define _SYS_SOCKETPAIR             53
    #define _SYS_SETSOCKOPT             54
    #define _SYS_GETSOCKOPT             55
    #define _SYS_CLONE                  56
    #define _SYS_FORK                   57
    #define _SYS_VFORK                  58
    #define _SYS_EXECVE                 59
    #define _SYS_EXIT                   60
    #define _SYS_WAIT4                  61
    #define _SYS_KILL                   62
    #define _SYS_UNAME                  63
    #define _SYS_SEMGET                 64
    #define _SYS_SEMOP                  65
    #define _SYS_SEMCTL                 66
    #define _SYS_SHMDT                  67
    #define _SYS_MSGGET                 68
    #define _SYS_MSGSND                 69
    #define _SYS_MSGRCV                 70
    #define _SYS_MSGCTL                 71
    #define _SYS_FCNTL                  72
    #define _SYS_FLOCK                  73
    #define _SYS_FSYNC                  74
    #define _SYS_FDATASYNC              75
    #define _SYS_TRUNCATE               76
    #define _SYS_FTRUNCATE              77
    #define _SYS_GETDENTS               78
    #define _SYS_GETCWD                 79
    #define _SYS_CHDIR                  80
    #define _SYS_FCHDIR                 81
    #define _SYS_RENAME                 82
    #define _SYS_MKDIR                  83
    #define _SYS_RMDIR                  84
    #define _SYS_CREAT                  85
    #define _SYS_LINK                   86
    #define _SYS_UNLINK                 87
    #define _SYS_SYMLINK                88
    #define _SYS_READLINK               89
    #define _SYS_CHMOD                  90
    #define _SYS_FCHMOD                 91
    #define _SYS_CHOWN                  92
    #define _SYS_FCHOWN                 93
    #define _SYS_LCHOWN                 94
    #define _SYS_UMASK                  95
    #define _SYS_GETTIMEOFDAT           96
    #define _SYS_GETRLIMIT              97
    #define _SYS_GETRUSAGE              98
    #define _SYS_SYSINFO                99
    #define _SYS_TIMES                  100
    #define _SYS_PTRACE                 101
    #define _SYS_GETUID                 102
    #define _SYS_SYSLOG                 103
    #define _SYS_GETGID                 104
    #define _SYS_SETUID                 105
    #define _SYS_SETGID                 106
    #define _SYS_GETEUID                107
    #define _SYS_GETEGID                108
    #define _SYS_SETPGID                109
    #define _SYS_GETPPID                110
    #define _SYS_GETPGRP                111
    #define _SYS_SETSID                 112
    #define _SYS_SETREUID               113
    #define _SYS_SETREGID               114
    #define _SYS_GETGROUPS              115
    #define _SYS_SETGROUPS              116
    #define _SYS_SETRESUID              117
    #define _SYS_GETRESUID              118
    #define _SYS_SETRESGID              119
    #define _SYS_GETRESGID              120
    #define _SYS_GETPGID                121
    #define _SYS_SETFSUID               122
    #define _SYS_SETFSGID               123
    #define _SYS_GETSID                 124
    #define _SYS_CAPGET                 125
    #define _SYS_CATSET                 126
    #define _SYS_RT_SIGPENDING          127
    #define _SYS_RT_SIGTIMEDWAIT        128
    #define _SYS_RT_SIGQUEUEINFO        129
    #define _SYS_RT_SIGSUSPEND          130
    #define _SYS_SIGALTSTACK            131
    #define _SYS_UTIME                  132
    #define _SYS_MKNOD                  133
    #define _SYS_USELIB                 134
    #define _SYS_PERSONALITY            135
    #define _SYS_USTAT                  136
    #define _SYS_STATFS                 137
    #define _SYS_FSTATFS                138
    #define _SYS_SYSFS                  139
    #define _SYS_GETPRIORITY            140
    #define _SYS_SETPRIORITY            141
    #define _SYS_SCHED_SETPARAM         142
    #define _SYS_SCHED_GETPARAM         143
    #define _SYS_SCHED_SETSCHEDULER     144
    #define _SYS_SCHED_GETSCHEDULAR     145
    #define _SYS_SCHED_GET_PRIORITY_MAX 146
    #define _SYS_SCHED_GET_PRIORITY_MIN 147
    #define _SYS_SCHED_RR_GET_INTERVAL  148
    #define _SYS_MLOCK                  149
    #define _SYS_MINLOCK                150
    #define _SYS_MLOCKALL               151
    #define _SYS_MUNLOCKALL             152
    #define _SYS_VHANGUP                153
    #define _SYS_MODIFY_LDT             154
    #define _SYS_PIVOT_ROOT             155
    #define _SYS__SYSCTL                156
    #define _SYS_PRCTL                  157
    #define _SYS_ARCH_PRCTL             158
    #define _SYS_ADJTIMEX               159
    #define _SYS_SETRLIMIT              160
    #define _SYS_CHROOT                 161
    #define _SYS_SYNC                   162
    #define _SYS_ACCT                   163
    #define _SYS_SETTIMEOFDAY           164
    #define _SYS_MOUNT                  165
    #define _SYS_UMOUNT2                166
    #define _SYS_SWAPON                 167
    #define _SYS_SWAPOFF                168
    #define _SYS_REBOOT                 169
    #define _SYS_SETHOSTNAME            170
    #define _SYS_SETDOMAINNAME          171
    #define _SYS_IOPL                   172
    #define _SYS_IOPERM                 173
    #define _SYS_CREATE_MODULE          174
    #define _SYS_INIT_MODULE            175
    #define _SYS_DELETE_MODULE          176
    #define _SYS_GET_KERNEL_SYMS        177
    #define _SYS_QUERY_MODULE           178
    #define _SYS_QUOTACTL               179
    #define _SYS_NFSSERVCTL             180
    #define _SYS_GETPMSG                181
    #define _SYS_PUTPMSG                182
    #define _SYS_AFS_SYSCALL            183
    #define _SYS_TUXCALL                184
    #define _SYS_SECURITY               185
    #define _SYS_GETTID                 186
    #define _SYS_READAHEAD              187
    #define _SYS_SETXATTR               188
    #define _SYS_LSETXATTR              189
    #define _SYS_FSETXATTR              190
    #define _SYS_GETXATTR               191
    #define _SYS_LGETXATTR              192
    #define _SYS_FGETXATTR              193
    #define _SYS_LISTXATTR              194
    #define _SYS_LLISTXATTR             195
    #define _SYS_FLISTXATTR             196
    #define _SYS_REMOVEXATTR            197
    #define _SYS_LREMOVEXATTR           198
    #define _SYS_FREMOVEXATTR           199
    #define _SYS_TKILL                  200
    #define _SYS_TIME                   201
    #define _SYS_FUTEX                  202
    #define _SYS_SCHED_SETAFFINITY      203
    #define _SYS_SCHED_GETAFFINITY      204
    #define _SYS_SET_THREAD_AREA        205
    #define _SYS_IO_SETUP               206
    #define _SYS_IO_DESTROY             207
    #define _SYS_IO_GETEVENTS           208
    #define _SYS_IO_SUBMIT              209
    #define _SYS_IO_CANCEL              210
    #define _SYS_GET_THREAD_AREA        211
    #define _SYS_LOOKUP_DCOOKIE         212
    #define _SYS_EPOLL_CREATE           213
    #define _SYS_EPOLL_CTL_OLD          214
    #define _SYS_EPOLL_WAIT_OLD         215
    #define _SYS_REMAP_FILE_PAGES       216
    #define _SYS_GETDENTS64             217
    #define _SYS_SET_TID_ADDRESS        218
    #define _SYS_RESTART_SYSCALL        219
    #define _SYS_SETTIMEDOP             220
    #define _SYS_FADVISE64              221
    #define _SYS_TIMER_CREATE           222
    #define _SYS_TIMER_SETTIME          223
    #define _SYS_TIMER_GETTIME          224
    #define _SYS_TIMER_GETOVERRUN       225
    #define _SYS_TIMER_DELETE           226
    #define _SYS_CLOCK_SETTIME          227
    #define _SYS_CLOCK_GETTIME          228
    #define _SYS_CLOCK_GETRES           229
    #define _SYS_CLOCK_NANOSLEEP        230
    #define _SYS_EXIT_GROUP             231
    #define _SYS_EPOLL_WAIT             232
    #define _SYS_EPOLL_CTL              233
    #define _SYS_TGKILL                 234
    #define _SYS_UTIMES                 235
    #define _SYS_VSERVER                236
    #define _SYS_MBIND                  237
    #define _SYS_SET_MEMPOLICY          238
    #define _SYS_GET_MEMPOLICY          239
    #define _SYS_MQ_OPEN                240
    #define _SYS_MQ_UNLINK              241
    #define _SYS_MQ_TIMEDSEND           242
    #define _SYS_MQ_TIMEDRECEIVE        243
    #define _SYS_MQ_NOTIFY              244
    #define _SYS_MQ_GETSETATTR          245
    #define _SYS_KEXEC_LOAD             246
    #define _SYS_WAITID                 247
    #define _SYS_ADD_KEY                248
    #define _SYS_REQUEST_KEY            249
    #define _SYS_KEYCTL                 250
    #define _SYS_IOPRIO_SET             251
    #define _SYS_IOPRIO_GET             252
    #define _SYS_INOTIFY_INIT           253
    #define _SYS_INOTIFY_ADD_WATCH      254
    #define _SYS_INOTIFY_RM_WATCH       255
    #define _SYS_MIGRATE_PAGES          256
    #define _SYS_OPENAT                 257
    #define _SYS_MKDIRAT                258
    #define _SYS_MKNODAT                259
    #define _SYS_FCHOWNAT               260
    #define _SYS_FUTIMESAY              261
    #define _SYS_NEWFSTATAT             262
    #define _SYS_UNLINKAT               263
    #define _SYS_RENAMEAT               264
    #define _SYS_LINKAT                 265
    #define _SYS_SYMLINKAT              266
    #define _SYS_READLINKAT             267
    #define _SYS_FCHMODAT               268
    #define _SYS_FACCESSAT              269
    #define _SYS_PSELECT6               270
    #define _SYS_PPOLL                  271
    #define _SYS_UNSHARE                272
    #define _SYS_SET_ROBUST_LIST        273
    #define _SYS_GET_ROBUST_LIST        274
    #define _SYS_SPLICE                 275
    #define _SYS_TEE                    276
    #define _SYS_SYNC_FILE_RANGE        277
    #define _SYS_VMSPLICE               278
    #define _SYS_MOVE_PAGES             279
    #define _SYS_UTIMENSAT              280
    #define _SYS_EPOLL_PWAIT            281
    #define _SYS_SIGNALFD               282
    #define _SYS_TIMERFD_CREATE         283
    #define _SYS_EVENTFD                284
    #define _SYS_FALLOCATE              285
    #define _SYS_TIMERFD_SETTIME        286
    #define _SYS_TIMERFD_GETTIME        287
    #define _SYS_ACCEPT4                288
    #define _SYS_SIGNALFD4              289
    #define _SYS_EVENTFD2               290
    #define _SYS_EPOLL_CREATE1          291
    #define _SYS_DUP3                   292
    #define _SYS_PIPE2                  293
    #define _SYS_INOTIFY_INIT1          294
    #define _SYS_PREADV                 295
    #define _SYS_PWRITEV                296
    #define _SYS_RT_TGSIGQUEUEINFO      297
    #define _SYS_PERF_EVENT_OPEN        298
    #define _SYS_RECVMMSG               299
    #define _SYS_FANOTIFY_INIT          300
    #define _SYS_FANOTIFY_MARK          301
    #define _SYS_PRLIMIT64              302
    #define _SYS_NAME_TO_HANDLE_AT      303
    #define _SYS_OPEN_BY_HANDLE_AT      304
    #define _SYS_CLOCK_ADJTIME          305
    #define _SYS_SYNCFS                 306
    #define _SYS_SENDMMSG               307
    #define _SYS_SETNS                  308
    #define _SYS_GETCPU                 309
    #define _SYS_PROCESS_VM_READV       310
    #define _SYS_PROVESS_VM_WRITEV      311
    #define _SYS_KCMP                   312
    #define _SYS_FINIT_MODULE           313
    #define _SYS_SCHED_SETATTR          314
    #define _SYS_SCHED_GETATTR          315
    #define _SYS_RENAMEAT2              316
    #define _SYS_SECCOMP                317
    #define _SYS_GETRANDOM              318
    #define _SYS_MEMFD_CREATE           319
    #define _SYS_KEXEC_FILE_LOAD        320
    #define _SYS_BPF                    321
    #define STUB_EXECVEAT               322
    #define USERFAULTFD                 323
    #define MEMBARRIER                  324
    #define MLOCK2                      325
    #define COPY_FILE_RANGE             326
    #define PREADV2                     327
    #define PWRITEV2                    328
    #define PKEY_MPROTECT               329
    #define PKEY_ALLOC                  330
    #define PKEY_FREE                   331
    #define STATX                       332
    #define IO_PGETEVENTS               333
    #define RSEQ                        334
    #define PKEY_MPROTECT2              335
#endif

#if defined(__X86__)
    // C Calling Conventions
    #define __EAX__ "eax"
    #define __EBX__ "ebx"
    #define __ECX__ "ecx"
    #define __EDX__ "edx"
    #define __ESI__ "esi"
    #define __EDI__ "edi"

    #define __EBP__ "ebp"
    #define __ESP__ "esp"
#elif defined(__X86_64__)
    // C Calling Conventions
    #define __RAX__ "rax"
    #define __RDI__ "rdi"
    #define __RSI__ "rsi"
    #define __RDX__ "rdx"
    #define __R10__ "r10"
    #define __R8__ "r8"
    #define __R9__ "r9"

    // Spare Registers
    #define __RBX__ "rbx"
    #define __RCX__ "rcx"
    #define __RBP__ "rbp"
    #define __R15__ "r15"
    #define __R14__ "r14"
    #define __R13__ "r13"
    #define __R12__ "r12"
    #define __R11__ "r11"

    // Stack pointer
    #define __RSP__ "rsp"
#endif
